"""initial_schema

Revision ID: 167ec731a9d1
Revises: 
Create Date: 2026-07-17 19:33:15.626639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '167ec731a9d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('group_name', sa.String(length=10), nullable=False),
    sa.Column('flag_url', sa.Text(), nullable=True),
    sa.Column('fifa_ranking', sa.Integer(), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=False),
    sa.Column('recent_form_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('goals_for', sa.Integer(), server_default='0', nullable=False),
    sa.Column('goals_against', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('draws', sa.Integer(), server_default='0', nullable=False),
    sa.Column('losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extra_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'finished', 'cancelled', name='matchstatus'), server_default='scheduled', nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('home_team_id != away_team_id', name='ck_match_different_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_matches_kickoff_at', 'matches', ['kickoff_at'], unique=False)
    op.create_index('ix_matches_status', 'matches', ['status'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('predicted_outcome', sa.Enum('home_win', 'away_win', 'draw', name='predictedoutcome'), nullable=False),
    sa.Column('predicted_home_score', sa.Integer(), nullable=True),
    sa.Column('predicted_away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'session_id', name='uq_prediction_match_session')
    )
    op.create_index('ix_predictions_match_id', 'predictions', ['match_id'], unique=False)
    op.create_index('ix_predictions_session_id', 'predictions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_session_id', table_name='predictions')
    op.drop_index('ix_predictions_match_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_matches_status', table_name='matches')
    op.drop_index('ix_matches_kickoff_at', table_name='matches')
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
